import { ColorSetting, PebbleColor } from './types';

// Color settings configuration
export const colorSettings: ColorSetting[] = [
  { baseId: 'TIME_COLOR', label: 'Time Color', default: '#000000' },
  { baseId: 'SUBTEXT_PRIMARY_COLOR', label: 'Date Color', default: '#000000' },
  { baseId: 'SUBTEXT_SECONDARY_COLOR', label: 'Widget Text Color', default: '#555555' },
  { baseId: 'BG_COLOR', label: 'Background Color', default: '#FFFFFF' },
  { baseId: 'PIP_COLOR_PRIMARY', label: 'Pip Color (Primary)', default: '#000000' },
  { baseId: 'PIP_COLOR_SECONDARY', label: 'Pip Color (Secondary)', default: '#AAAAAA' },
  { baseId: 'RING_STROKE_COLOR', label: 'Ring Outline Color', default: '#000000' },
  { baseId: 'RING_NIGHT_COLOR', label: 'Ring Color: Night', default: '#0055AA' },
  { baseId: 'RING_DAY_COLOR', label: 'Ring Color: Day', default: '#00AAFF' },
  { baseId: 'RING_SUNRISE_COLOR', label: 'Ring Color: Sunrise', default: '#FFAAAA' },
  { baseId: 'RING_SUNSET_COLOR', label: 'Ring Color: Sunset', default: '#FFAA00' },
  { baseId: 'SUN_STROKE_COLOR', label: 'Sun Outline Color', default: '#000000' },
  { baseId: 'SUN_FILL_COLOR', label: 'Sun Color', default: '#FFFF00' },
];

// Pebble Color Palette (64 colors)
export const pebbleColors: { [hex: string]: PebbleColor } = {
  '#AAFFAA': { name: 'Mint Green', identifier: 'MintGreen' },
  '#FFAAAA': { name: 'Melon', identifier: 'Melon' },
  '#FF55FF': { name: 'Shocking Pink (Crayola)', identifier: 'ShockingPink' },
  '#FF0055': { name: 'Folly', identifier: 'Folly' },
  '#FF5555': { name: 'Sunset Orange', identifier: 'SunsetOrange' },
  '#555500': { name: 'Army Green', identifier: 'ArmyGreen' },
  '#0000AA': { name: 'Duke Blue', identifier: 'DukeBlue' },
  '#00AAAA': { name: 'Tiffany Blue', identifier: 'TiffanyBlue' },
  '#55FF55': { name: "Screamin' Green", identifier: 'ScreaminGreen' },
  '#FFFFAA': { name: 'Pastel Yellow', identifier: 'PastelYellow' },
  '#FFAAFF': { name: 'Rich Brilliant Lavender', identifier: 'RichBrilliantLavender' },
  '#55FF00': { name: 'Bright Green', identifier: 'BrightGreen' },
  '#FF55AA': { name: 'Brilliant Rose', identifier: 'BrilliantRose' },
  '#55AAAA': { name: 'Cadet Blue', identifier: 'CadetBlue' },
  '#AA5555': { name: 'Rose Vale', identifier: 'RoseVale' },
  '#FF00AA': { name: 'Fashion Magenta', identifier: 'FashionMagenta' },
  '#00AA55': { name: 'Jaeger Green', identifier: 'JaegerGreen' },
  '#AAAAFF': { name: 'Baby Blue Eyes', identifier: 'BabyBlueEyes' },
  '#AA55AA': { name: 'Purpureus', identifier: 'Purpureus' },
  '#FFAA00': { name: 'Chrome Yellow', identifier: 'ChromeYellow' },
  '#005500': { name: 'Dark Green (X11)', identifier: 'DarkGreen' },
  '#FF0000': { name: 'Red', identifier: 'Red' },
  '#5555AA': { name: 'Liberty', identifier: 'Liberty' },
  '#AAAAAA': { name: 'Light Gray', identifier: 'LightGray' },
  '#AA00FF': { name: 'Vivid Violet', identifier: 'VividViolet' },
  '#FFAA55': { name: 'Rajah', identifier: 'Rajah' },
  '#5500AA': { name: 'Indigo (Web)', identifier: 'Indigo' },
  '#55AA55': { name: 'May Green', identifier: 'MayGreen' },
  '#FFFF55': { name: 'Icterine', identifier: 'Icterine' },
  '#550000': { name: 'Bulgarian Rose', identifier: 'BulgarianRose' },
  '#FF5500': { name: 'Orange', identifier: 'Orange' },
  '#00FF00': { name: 'Green', identifier: 'Green' },
  '#AA5500': { name: 'Windsor Tan', identifier: 'WindsorTan' },
  '#AA55FF': { name: 'Lavender Indigo', identifier: 'LavenderIndigo' },
  '#555555': { name: 'Dark Gray', identifier: 'DarkGray' },
  '#55FFFF': { name: 'Electric Blue', identifier: 'ElectricBlue' },
  '#0055FF': { name: 'Blue Moon', identifier: 'BlueMoon' },
  '#00FFFF': { name: 'Cyan', identifier: 'Cyan' },
  '#000000': { name: 'Black', identifier: 'Black' },
  '#55FFAA': { name: 'Medium Aquamarine', identifier: 'MediumAquamarine' },
  '#AA0000': { name: 'Dark Candy Apple Red', identifier: 'DarkCandyAppleRed' },
  '#AAAA00': { name: 'Limerick', identifier: 'Limerick' },
  '#0055AA': { name: 'Cobalt Blue', identifier: 'CobaltBlue' },
  '#AAFFFF': { name: 'Celeste', identifier: 'Celeste' },
  '#5500FF': { name: 'Electric Ultramarine', identifier: 'ElectricUltramarine' },
  '#55AAFF': { name: 'Picton Blue', identifier: 'PictonBlue' },
  '#AAFF55': { name: 'Inchworm', identifier: 'Inchworm' },
  '#0000FF': { name: 'Blue', identifier: 'Blue' },
  '#00AAFF': { name: 'Vivid Cerulean', identifier: 'VividCerulean' },
  '#AA00AA': { name: 'Purple', identifier: 'Purple' },
  '#55AA00': { name: 'Kelly Green', identifier: 'KellyGreen' },
  '#00FF55': { name: 'Malachite', identifier: 'Malachite' },
  '#005555': { name: 'Midnight Green (Eagle Green)', identifier: 'MidnightGreen' },
  '#FFFF00': { name: 'Yellow', identifier: 'Yellow' },
  '#FF00FF': { name: 'Magenta', identifier: 'Magenta' },
  '#AAFF00': { name: 'Spring Bud', identifier: 'SpringBud' },
  '#AA0055': { name: 'Jazzberry Jam', identifier: 'JazzberryJam' },
  '#5555FF': { name: 'Very Light Blue', identifier: 'VeryLightBlue' },
  '#FFFFFF': { name: 'White', identifier: 'White' },
  '#00AA00': { name: 'Islamic Green', identifier: 'IslamicGreen' },
  '#000055': { name: 'Oxford Blue', identifier: 'OxfordBlue' },
  '#550055': { name: 'Imperial Purple', identifier: 'ImperialPurple' },
  '#AAAA55': { name: 'Brass', identifier: 'Brass' },
  '#00FFAA': { name: 'Medium Spring Green', identifier: 'MediumSpringGreen' },
};

// Custom color order with blanks
export const colorOrder: (string | null)[] = [
  '#000000',
  '#555555',
  '#AAAAAA',
  '#FFFFFF',
  null,
  null,
  null,
  null,
  null,
  '#FF0055',
  null,
  null,
  '#AA5555',
  '#550000',
  '#AA0000',
  '#FF0000',
  '#FF5555',
  '#FFAAAA',
  null,
  null,
  null,
  '#FF5500',
  null,
  null,
  null,
  null,
  '#AA5500',
  '#FFAA00',
  '#FFAA55',
  null,
  '#AAAA55',
  '#555500',
  '#AAAA00',
  '#FFFF00',
  '#FFFF55',
  '#FFFFAA',
  null,
  null,
  '#55AA00',
  '#AAFF00',
  '#AAFF55',
  null,
  null,
  null,
  null,
  '#55FF00',
  null,
  null,
  '#55AA55',
  '#005500',
  '#00AA00',
  '#00FF00',
  '#55FF55',
  '#AAFFAA',
  null,
  null,
  null,
  '#00FF55',
  null,
  null,
  null,
  null,
  '#00AA55',
  '#00FFAA',
  '#55FFAA',
  null,
  '#55AAAA',
  '#005555',
  '#00AAAA',
  '#00FFFF',
  '#55FFFF',
  '#AAFFFF',
  null,
  null,
  '#0055AA',
  '#00AAFF',
  '#55AAFF',
  null,
  null,
  null,
  null,
  '#0055FF',
  null,
  null,
  '#5555AA',
  '#000055',
  '#0000AA',
  '#0000FF',
  '#5555FF',
  '#AAAAFF',
  null,
  null,
  null,
  '#5500FF',
  null,
  null,
  null,
  null,
  '#5500AA',
  '#AA00FF',
  '#AA55FF',
  null,
  '#AA55AA',
  '#550055',
  '#AA00AA',
  '#FF00FF',
  '#FF55FF',
  '#FFAAFF',
  null,
  null,
  '#AA0055',
  '#FF00AA',
  '#FF55AA',
  null,
];

// BW color orders
export const bwFillColorOrder: string[] = ['#000000', '#FFFFFF', '#AAAAAA'];

export const bwStrokeColorOrder: string[] = ['#000000', '#FFFFFF'];

// Stroke/text fields that can only be black or white on BW platforms
export const bwStrokeFields: Set<string> = new Set([
  'SUN_STROKE_COLOR',
  'RING_STROKE_COLOR',
  'PIP_COLOR_PRIMARY',
  'PIP_COLOR_SECONDARY',
  'TIME_COLOR',
  'SUBTEXT_PRIMARY_COLOR',
  'SUBTEXT_SECONDARY_COLOR',
]);

// Theme display names
export const themeDisplayNames: { [key: string]: string } = {
  default: 'Solar Solarson',
  orangeDreams: 'Orange Dreams',
  terminalGreen: 'Terminal Green',
  lightOceanTheme: 'Light Ocean',
  roseTheme: 'Rose',
  fireworkTheme: 'Firework',
  oceanTheme: 'Ocean',
  mauveTheme: 'Mauve',
  sandTheme: 'Sand',
  greyTheme: 'Grey',
  userTeal1: 'Teal',
  bwTheme1: 'Black & White',
  bwTheme2: 'Black & White 2',
  bwTheme3: 'Black & White 3',
  bwTheme4: 'Black & White 4',
  custom: 'Custom',
};

// Global variable for BW platform detection
export let isBWPlatform = false;
export const setIsBWPlatform = (value: boolean) => {
  isBWPlatform = value;
};
